-- ============================================================
-- SANKARA NIGERIA LIMITED - COMPLETE DATABASE RESTORE SCRIPT
-- ============================================================


CREATE TABLE IF NOT EXISTS public.users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    email_verified_at TIMESTAMP NULL,
    password VARCHAR(255) NOT NULL,
    api_token VARCHAR(255) NULL,
    remember_token VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    permissions TEXT NULL
);

CREATE TABLE IF NOT EXISTS public.categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    image VARCHAR(255) NULL,
    description TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS public.products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NULL,
    description TEXT NULL,
    price VARCHAR(255) NULL,
    image TEXT NULL,
    images TEXT NULL,
    specs TEXT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'Active',
    task VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    is_new_arrival BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS public.services (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    icon VARCHAR(255) NULL,
    description TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS public.gallery_items (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NULL,
    category VARCHAR(255) NULL,
    image TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    video_url VARCHAR(255) NULL,
    description TEXT NULL,
    date VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS public.activities (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NULL,
    date VARCHAR(255) NULL,
    content TEXT NULL,
    image TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    summary VARCHAR(255) NULL,
    category VARCHAR(255) NULL,
    video_url VARCHAR(255) NULL,
    description TEXT NULL
);

ALTER TABLE public.activities ALTER COLUMN date TYPE VARCHAR(255) USING date::VARCHAR;

CREATE TABLE IF NOT EXISTS public.portfolio_projects (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NULL,
    client VARCHAR(255) NULL,
    description TEXT NULL,
    image TEXT NULL,
    completion_date VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    year VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS public.team_members (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NULL,
    image TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.inquiries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NULL,
    message TEXT NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'Pending',
    date VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS public.activity_logs (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NULL,
    user_name VARCHAR(255) NULL,
    action VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    ip_address VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS public.api_request_logs (
    id SERIAL PRIMARY KEY,
    method VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    status_code INTEGER NOT NULL,
    duration_ms INTEGER NOT NULL,
    ip_address VARCHAR(255) NULL,
    payload TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Restore users (1 records)
INSERT INTO public."users" ("id", "name", "email", "email_verified_at", "password", "api_token", "remember_token", "created_at", "updated_at", "permissions") VALUES (1, 'Admin', 'admin@sankara.com', NULL, '$2y$12$rnsVeaMk4qMDklQCeUxZBuuWgTuymg5LmrgWrMCLSTb.ZnVfTmEtS', 'sankara_super_secret_token_123', NULL, '2026-07-07 19:38:14', '2026-07-07 19:39:13', NULL) ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('public.users', 'id'), COALESCE((SELECT MAX(id) FROM public.users), 1));

-- Restore products (26 records)
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (1, '13HP Tata Power Tiller', 'Specialized Equipment', 'Providing nearly double the power of the smaller model, the 13HP Tata Power Tiller handles tough, compacted soils with ease. It supports deeper row-tilling and can pull small farm carts, making it a rugged and versatile primary tool for medium-scale vegetable farms.', 'Price on Request', '/assets/products_staging/OTHER/13HP Tata Power Tiller/WhatsApp Image 2026-07-09 at 11.34.23 AM.jpeg', '["\/assets\/products_staging\/OTHER\/13HP Tata Power Tiller\/WhatsApp Image 2026-07-09 at 11.34.23 AM.jpeg","\/assets\/products_staging\/OTHER\/13HP Tata Power Tiller\/WhatsApp Image 2026-07-09 at 11.34.30 AM.jpeg"]', '["13 HP Heavy-Duty Engine","Dual-Speed Transmission","Extra-Wide Rotary Tines","Reinforced Mechanical Frame"]', 'Active', 'Medium-scale soil cultivation, rotary plowing, and hauling in smallholder fields or hard clay soils.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (2, '4-Row Corn Harvester Header', 'Specialized Equipment', 'This high-performance 4-Row Corn Harvester Header is engineered for seamless integration with combine harvesters. It cleanly separates corn ears from stalks, directing them into the feeder house while leaving chopped stalks on the field, maximizing efficiency during the harvest season.', 'Price on Request', '/assets/products_staging/OTHER/4 ROW CORN HARVESTER HEADER/WhatsApp Image 2026-07-09 at 11.34.04 AM (1).jpeg', '["\/assets\/products_staging\/OTHER\/4 ROW CORN HARVESTER HEADER\/WhatsApp Image 2026-07-09 at 11.34.04 AM (1).jpeg","\/assets\/products_staging\/OTHER\/4 ROW CORN HARVESTER HEADER\/WhatsApp Image 2026-07-09 at 11.34.04 AM.jpeg","\/assets\/products_staging\/OTHER\/4 ROW CORN HARVESTER HEADER\/WhatsApp Image 2026-07-09 at 11.34.22 AM (1).jpeg"]', '["4-Row Harvesting Capacity","High-Strength Steel Construction","Compatible with Major Combine Harvesters","Optimized Row Spacing"]', 'Active', 'Efficiently snapping and harvesting corn ears from stalks while minimizing grain damage and field loss.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (3, '7HP Tata Power Tiller', 'Specialized Equipment', 'The 7HP Tata Power Tiller is a light, agile walk-behind cultivator built for intensive work in tight spaces. Perfect for smallholders and vegetable gardeners, it breaks up topsoil and cuts down weeds with minimal user effort, navigating narrow pathways where full-sized tractors cannot fit.', 'Price on Request', '/assets/products_staging/OTHER/7HP Tata Power Tiller/WhatsApp Image 2026-07-09 at 11.34.24 AM (1).jpeg', '["\/assets\/products_staging\/OTHER\/7HP Tata Power Tiller\/WhatsApp Image 2026-07-09 at 11.34.24 AM (1).jpeg","\/assets\/products_staging\/OTHER\/7HP Tata Power Tiller\/WhatsApp Image 2026-07-09 at 11.34.29 AM (1).jpeg"]', '["7 HP Gasoline\/Diesel Engine","Compact Walking Frame","Multi-Blade Rotary Tines","Adjustable Handlebars"]', 'Active', 'Small-scale soil tilling, weeding, and seedbed preparation in home gardens, narrow orchards, and greenhouses.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (4, 'Bamford Baler', 'Specialized Equipment', 'The Bamford Baler is an essential implement for managing post-harvest straw and livestock forage. It cleans fields by pulling in loose material, compacting it inside a high-density chamber, and securing it with an automated knotting mechanism. The resulting uniform bales are easy to transport and store over long winters.', 'Price on Request', '/assets/products_staging/OTHER/Bamford Baler/BamfordBaler-x1zE2RlD.jpeg', '["\/assets\/products_staging\/OTHER\/Bamford Baler\/BamfordBaler-x1zE2RlD.jpeg"]', '["High-Density Compression Chamber","Automated Knotter System","Adjustable Bale Size","PTO Driven"]', 'Active', 'Gathering and compressing loose hay, straw, or forage into compact, transportable, and stackable bales.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (5, 'Bamford Forage Harvester (Chopper)', 'Specialized Equipment', 'This tractor-driven forage harvester cuts green standing crops and immediately processes them through a high-speed chopping mechanism. It guarantees uniform chop lengths, which optimizes anaerobic compaction during silage fermentation, improving the overall nutritional retention of livestock feed.', 'Price on Request', '/assets/products_staging/OTHER/Bamford Forage Harvester (Chopper)/BamfordForageHarvesterChopper-DfRrIS-T.jpeg', '["\/assets\/products_staging\/OTHER\/Bamford Forage Harvester (Chopper)\/BamfordForageHarvesterChopper-DfRrIS-T.jpeg","\/assets\/products_staging\/OTHER\/Bamford Forage Harvester (Chopper)\/WhatsApp Image 2026-07-09 at 11.34.01 AM.jpeg"]', '["PTO Driven","High-Speed Cutting Flywheel","Adjustable Chop Length","Directional Discharge Chute"]', 'Active', 'Cutting and fine-chopping green fodder crops (such as maize or sorghum) for high-quality silage production.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (6, 'Multi-Crop Thresher', 'Specialized Equipment', 'The Multi-Crop Thresher is a robust post-harvest machine designed to separate grain from chaff. Powered by a tractor PTO or an auxiliary engine, it processes harvested stalks, yielding clean, polished grain with minimal kernel damage, dramatically cutting down manual threshing labor.', 'Price on Request', '/assets/products_staging/OTHER/THRESHER/WhatsApp Image 2026-07-09 at 11.33.51 AM.jpeg', '["\/assets\/products_staging\/OTHER\/THRESHER\/WhatsApp Image 2026-07-09 at 11.33.51 AM.jpeg","\/assets\/products_staging\/OTHER\/THRESHER\/WhatsApp Image 2026-07-09 at 11.34.05 AM.jpeg","\/assets\/products_staging\/OTHER\/THRESHER\/WhatsApp Image 2026-07-09 at 11.34.06 AM.jpeg"]', '["High-Speed Threshing Cylinder","Adjustable Blow Speed","Interchangeable Screen Sieves","Tractor PTO or Engine Powered"]', 'Active', 'Separating grains from harvested crops (maize, sorghum, rice, beans) rapidly and cleanly.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (7, 'Tata 2BYZF-4 No-Till Planter with Fertilizer Applicator', 'Specialized Equipment', 'The Tata 2BYZF-4 is an advanced 4-row planter engineered for conservation agriculture. Its sharp disc cutters cut through old crop residues to place seeds directly into the unplowed earth, while simultaneously laying down fertilizer. This method protects the soil structure and conserves ground moisture.', 'Price on Request', '/assets/products_staging/OTHER/Tata 2BYZF-4 No-Till Planter with Fertilizer Applicator/FertilizerApplicator4Planter--V26CKtd.jpeg', '["\/assets\/products_staging\/OTHER\/Tata 2BYZF-4 No-Till Planter with Fertilizer Applicator\/FertilizerApplicator4Planter--V26CKtd.jpeg","\/assets\/products_staging\/OTHER\/Tata 2BYZF-4 No-Till Planter with Fertilizer Applicator\/WhatsApp Image 2026-07-09 at 11.33.50 AM.jpeg","\/assets\/products_staging\/OTHER\/Tata 2BYZF-4 No-Till Planter with Fertilizer Applicator\/WhatsApp Image 2026-07-09 at 11.34.26 AM.jpeg","\/assets\/products_staging\/OTHER\/Tata 2BYZF-4 No-Till Planter with Fertilizer Applicator\/WhatsApp Image 2026-07-09 at 11.34.27 AM (1).jpeg","\/assets\/products_staging\/OTHER\/Tata 2BYZF-4 No-Till Planter with Fertilizer Applicator\/WhatsApp Image 2026-07-09 at 11.34.27 AM.jpeg"]', '["4-Row Seeding Assembly","No-Till Disc Openers","Integrated Dual Fertilizer Hoppers","Depth-Control Press Wheels"]', 'Active', 'Simultaneous direct seeding and precise fertilizer placement into unplowed crop fields in a single pass.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (8, 'Tata 2BYZF-6 No-Till Planter with Fertilizer Applicator', 'Specialized Equipment', 'This 6-row configuration maximizes planting efficiency for larger farming operations. It shares the same no-till design as the 4-row model, but features larger seed and fertilizer capacities to minimize refilling stops, allowing farmers to cover fields rapidly while preventing soil erosion.', 'Price on Request', '/assets/products_staging/OTHER/Tata 2BYZF-6 No-Till Planter with Fertilizer Applicator/FertilizerApplicator-DRJGsdIk.jpeg', '["\/assets\/products_staging\/OTHER\/Tata 2BYZF-6 No-Till Planter with Fertilizer Applicator\/FertilizerApplicator-DRJGsdIk.jpeg","\/assets\/products_staging\/OTHER\/Tata 2BYZF-6 No-Till Planter with Fertilizer Applicator\/WhatsApp Image 2026-07-09 at 11.34.00 AM.jpeg","\/assets\/products_staging\/OTHER\/Tata 2BYZF-6 No-Till Planter with Fertilizer Applicator\/WhatsApp Image 2026-07-09 at 11.34.23 AM (1).jpeg","\/assets\/products_staging\/OTHER\/Tata 2BYZF-6 No-Till Planter with Fertilizer Applicator\/WhatsApp Image 2026-07-09 at 11.34.24 AM.jpeg"]', '["6-Row Seeding Assembly","Heavy-Duty No-Till Disc Coulters","Large Capacity Seed\/Fertilizer Tanks","Precision Metering Units"]', 'Active', 'High-capacity direct seeding and fertilizer application across larger acreage fields to preserve soil moisture.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (9, 'Tata 6N2018X-G Rice Mill', 'Specialized Equipment', 'The Tata 6N2018X-G is an efficient, all-in-one rice milling machine built for decentralized agricultural processing. It gently separates the tough outer husk from raw paddy grains before running them through an integrated polishing system, producing clean, high-grade white rice with a very low percentage of broken grains.', 'Price on Request', '/assets/products_staging/OTHER/Tata 6N2018X-G Rice Mill/WhatsApp Image 2026-07-09 at 11.33.52 AM.jpeg', '["\/assets\/products_staging\/OTHER\/Tata 6N2018X-G Rice Mill\/WhatsApp Image 2026-07-09 at 11.33.52 AM.jpeg","\/assets\/products_staging\/OTHER\/Tata 6N2018X-G Rice Mill\/WhatsApp Image 2026-07-09 at 11.34.28 AM.jpeg","\/assets\/products_staging\/OTHER\/Tata 6N2018X-G Rice Mill\/WhatsApp Image 2026-07-09 at 11.34.29 AM.jpeg"]', '["Integrated De-husking System","Multistage Rice Polishing System","High-Output Electric Motor","Compact Footprint"]', 'Active', 'Processing harvested field paddy into fully de-husked, polished, and market-ready white rice.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (10, 'Tata Boom Sprayer', 'Specialized Equipment', 'The Tata Boom Sprayer provides uniform chemical coverage across a wide path, drastically reducing field time. It features adjustable nozzles to minimize chemical drift, ensuring targeted and efficient crop protection. Its durable boom arms fold compactly for safe transport between fields.', 'Price on Request', '/assets/products_staging/OTHER/Tata Boom Sprayer/TataBoomSprayer-DdUxDens.jpeg', '["\/assets\/products_staging\/OTHER\/Tata Boom Sprayer\/TataBoomSprayer-DdUxDens.jpeg"]', '["Tractor-Mounted Frame","Wide-Span Folding Booms","Adjustable Spray Nozzles","Chemical-Resistant Poly Tank"]', 'Active', 'Wide-coverage, precise application of liquid pesticides, liquid fertilizers, and herbicides across large crop fields.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (11, 'Tata Rice Transplanter', 'Specialized Equipment', 'This specialized machine replaces intensive manual labor by automatically planting young rice seedlings into wet paddies. It places seedlings at precise, uniform depths and intervals, ensuring optimal crop spacing that maximizes field yields while significantly lowering manual labor costs.', 'Price on Request', '/assets/products_staging/OTHER/Tata Rice Transplanter/RiceTransplanter-nXZtJxAL.jpeg', '["\/assets\/products_staging\/OTHER\/Tata Rice Transplanter\/RiceTransplanter-nXZtJxAL.jpeg"]', '["Mechanized Row Planting Fingers","Uniform Seedling Spacing","Low-Compaction Paddy Wheels","High-Speed Float Board"]', 'Active', 'Mechanized, high-speed transplanting of young rice seedlings into flooded paddy fields.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (12, 'Lovol Harvester RG108 (Standard Combine)', 'Combine Harvester', 'The Lovol RG108 is a robust combine harvester favored for its straightforward, reliable mechanical operation and excellent crop throughput. Its threshing mechanics cleanly separate grains from stalks, minimizing crop damage. The durable chassis and broad tires minimize soil compaction while keeping harvest operations smooth and highly efficient.', 'Price on Request', '/assets/products_staging/combine harvestor/LOVOL-RG108_Plus/WhatsApp Image 2026-07-09 at 11.33.11 AM.jpeg', '["\/assets\/products_staging\/combine harvestor\/LOVOL-RG108_Plus\/WhatsApp Image 2026-07-09 at 11.33.11 AM.jpeg","\/assets\/products_staging\/combine harvestor\/LOVOL-RG108_Plus\/WhatsApp Image 2026-07-09 at 11.33.13 AM.jpeg","\/assets\/products_staging\/combine harvestor\/LOVOL-RG108_Plus\/WhatsApp Image 2026-07-09 at 11.33.14 AM (1).jpeg","\/assets\/products_staging\/combine harvestor\/LOVOL-RG108_Plus\/WhatsApp Image 2026-07-09 at 11.33.14 AM.jpeg","\/assets\/products_staging\/combine harvestor\/LOVOL-RG108_Plus\/WhatsApp Image 2026-07-09 at 11.33.17 AM.jpeg","\/assets\/products_staging\/combine harvestor\/LOVOL-RG108_Plus\/WhatsApp Image 2026-07-09 at 11.33.18 AM.jpeg"]', '["Reliable Mechanical Drive","High-Volume Grain Tank","Optimized Cutting Width","Tangential Flow Threshing Drum"]', 'Active', 'Continuous harvesting of diverse grain crops including rice, wheat, and barley under varied climate conditions.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (13, 'Zoomlion Crawler Type Harvester ZL105', 'Combine Harvester', 'The Zoomlion ZL105 is built with heavy-duty crawler tracks specifically to operate where wheeled harvesters fail. It floats effortlessly over muddy soils and paddy environments, delivering exceptional stability and high traction. Its high-capacity harvesting drum processes dense wet crops cleanly, making it indispensable for intensive rice farming regions.', 'Price on Request', '/assets/products_staging/combine harvestor/ZOOMLION/WhatsApp Image 2026-07-09 at 11.33.18 AM (1).jpeg', '["\/assets\/products_staging\/combine harvestor\/ZOOMLION\/WhatsApp Image 2026-07-09 at 11.33.18 AM (1).jpeg","\/assets\/products_staging\/combine harvestor\/ZOOMLION\/WhatsApp Image 2026-07-09 at 11.33.19 AM.jpeg","\/assets\/products_staging\/combine harvestor\/ZOOMLION\/WhatsApp Image 2026-07-09 at 11.33.22 AM.jpeg","\/assets\/products_staging\/combine harvestor\/ZOOMLION\/WhatsApp Image 2026-07-09 at 11.33.49 AM.jpeg"]', '["High-Traction Crawler Tracks","High Ground Clearance","High-Capacity Grain Tank","Heavy-Duty Rubber Tracks","Turbocharged Engine"]', 'Active', 'Harvesting grain crops in waterlogged, muddy, or highly uneven and challenging wetland fields.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (14, 'Alvan Blanch Disc Harrow', 'Farm Implements', 'Manufactured by Alvan Blanch, this disc harrow is an exceptional tool for secondary cultivation. Following a primary plow, it pulverizes large dirt clods into a fine, flat tilth. It is highly adjustable to ensure full surface coverage, making it ideal for final seedbed preparation.', 'Price on Request', '/assets/products_staging/implements/Alvan Blanch Disc Harrow/OffsetDiscPlough-DO6luG0F.jpeg', '["\/assets\/products_staging\/implements\/Alvan Blanch Disc Harrow\/OffsetDiscPlough-DO6luG0F.jpeg","\/assets\/products_staging\/implements\/Alvan Blanch Disc Harrow\/WhatsApp Image 2026-07-09 at 11.33.49 AM (1).jpeg","\/assets\/products_staging\/implements\/Alvan Blanch Disc Harrow\/WhatsApp Image 2026-07-09 at 11.34.41 AM.jpeg"]', '["Premium Alvan Blanch Steel Structure","Multiple Heavy Discs","Adjustable Working Angle","Sealed Heavy-Duty Bearings"]', 'Active', 'High-quality secondary tillage, clod breaking, seedbed leveling, and active weed eradication.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (15, 'Disc Ridger', 'Farm Implements', 'The Disc Ridger utilizes heavy rotating discs to gather loose soil into perfectly shaped ridges. It is highly adjustable, allowing operators to match row spacing requirements for crops such as potatoes, maize, and vegetables, while creating neat channels that optimize field drainage.', 'Price on Request', '/assets/products_staging/implements/Disc Ridger/WhatsApp Image 2026-07-09 at 11.34.07 AM.jpeg', '["\/assets\/products_staging\/implements\/Disc Ridger\/WhatsApp Image 2026-07-09 at 11.34.07 AM.jpeg","\/assets\/products_staging\/implements\/Disc Ridger\/WhatsApp Image 2026-07-09 at 11.34.12 AM.jpeg","\/assets\/products_staging\/implements\/Disc Ridger\/WhatsApp Image 2026-07-09 at 11.34.41 AM (1).jpeg","\/assets\/products_staging\/implements\/Disc Ridger\/WhatsApp Image 2026-07-09 at 11.34.41 AM (2).jpeg"]', '["Adjustable Gang Angle","Durable Steel Discs","Heavy-Duty Frame","Variable Ridge Width Settings"]', 'Active', 'Creating uniform ridges and furrows for row crops, irrigation planning, and localized soil water management.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (16, 'Mould Board Plough', 'Farm Implements', 'The Mould Board Plough is the definitive tool for deep soil preparation. By cutting, lifting, and completely turning over the soil profile, it buries surface trash and weed seeds deep underground. This process enhances aeration, improves water infiltration, and establishes a clean, fertile seedbed.', 'Price on Request', '/assets/products_staging/implements/Mould Board Plough/MouldBoardPlough-roKwaKOA.jpeg', '["\/assets\/products_staging\/implements\/Mould Board Plough\/MouldBoardPlough-roKwaKOA.jpeg","\/assets\/products_staging\/implements\/Mould Board Plough\/WhatsApp Image 2026-07-09 at 11.33.59 AM.jpeg","\/assets\/products_staging\/implements\/Mould Board Plough\/WhatsApp Image 2026-07-09 at 11.34.40 AM (1).jpeg","\/assets\/products_staging\/implements\/Mould Board Plough\/WhatsApp Image 2026-07-09 at 11.34.40 AM.jpeg"]', '["Classic Mould Board Share Design","High-Clearance Frame","Deep Tillage Shares","Reversible or Fixed Configurations"]', 'Active', 'Traditional deep tillage, complete soil inversion, burial of organic crop residue, and weed seed suppression.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (17, 'Mould Board Ridger', 'Farm Implements', 'The Mould Board Ridger uses symmetric wings to plow through soil, pushing equal amounts to both sides to form raised beds. It provides deep soil penetration, ensuring that the root zone of the crop remains loosely packed and highly aerated, which is ideal for root crop health.', 'Price on Request', '/assets/products_staging/implements/Mould Board Ridger/MouldBoardRidger-CZahw9XL.jpeg', '["\/assets\/products_staging\/implements\/Mould Board Ridger\/MouldBoardRidger-CZahw9XL.jpeg"]', '["Dual Mould Board Wings","Deep Penetration Point","Adjustable Wing Span","High-Strength Steel Frame"]', 'Active', 'Forming deep, well-defined raised beds and clean furrows for crops requiring strict root drainage profiles.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (18, 'Offset Disc Plough', 'Farm Implements', 'The Offset Disc Plough is designed to aggressively penetrate tough, uncultivated soils where traditional shares might break. The heavy, sharp discs spin freely to slash through crop residue and blend it into the topsoil. It features highly adjustable angles to accommodate changing ground hardness levels.', 'Price on Request', '/assets/products_staging/implements/Offset Disc Plough/OffsetDiscPlough-DO6luG0F.jpeg', '["\/assets\/products_staging\/implements\/Offset Disc Plough\/OffsetDiscPlough-DO6luG0F.jpeg"]', '["Offset Frame Design","High-Carbon Steel Discs","Adjustable Cutting Depth","Heavy-Duty Scrapers"]', 'Active', 'Primary tillage in hard, dry, and stony soils, breaking up hardpan layers and chopping weed root systems.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (19, 'Shrubmaster Rotary Slasher', 'Farm Implements', 'The Shrubmaster Rotary Slasher is engineered to clear wild, untamed fields and scrublands. Driven by the tractor''s PTO, its heavy-duty blades rotate at high speeds to shred through thick brushwood and small saplings. It features built-in slip-clutch protection to safeguard the tractor''s internal drive from sudden subterranean impacts.', 'Price on Request', '/assets/products_staging/implements/Shrubmaster Rotary Slasher/ShrubmasterRotarySlasher-bgnnic4k.jpeg', '["\/assets\/products_staging\/implements\/Shrubmaster Rotary Slasher\/ShrubmasterRotarySlasher-bgnnic4k.jpeg","\/assets\/products_staging\/implements\/Shrubmaster Rotary Slasher\/WhatsApp Image 2026-07-09 at 11.33.54 AM.jpeg","\/assets\/products_staging\/implements\/Shrubmaster Rotary Slasher\/WhatsApp Image 2026-07-09 at 11.34.14 AM.jpeg","\/assets\/products_staging\/implements\/Shrubmaster Rotary Slasher\/WhatsApp Image 2026-07-09 at 11.34.15 AM.jpeg","\/assets\/products_staging\/implements\/Shrubmaster Rotary Slasher\/WhatsApp Image 2026-07-09 at 11.34.20 AM.jpeg","\/assets\/products_staging\/implements\/Shrubmaster Rotary Slasher\/WhatsApp Image 2026-07-09 at 11.34.22 AM.jpeg"]', '["Heavy-Duty Rotary Cutting Blades","Reinforced Steel Deck","Adjustable Skid Shoes","Friction Clutch Protection"]', 'Active', 'Heavy-duty clearing of tough field bushes, tall shrubs, overgrown vegetation, and pasture maintenance.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (20, 'Tipping Trailer', 'Farm Implements', 'This heavy-duty tipping trailer is built to handle the rigorous hauling needs of a busy farm. Operated directly by the tractor’s hydraulic system, its smooth tipping mechanism allows for rapid, effortless unloading of bulk materials. The reinforced steel box structure ensures long-term resistance to denting and heavy impacts.', 'Price on Request', '/assets/products_staging/implements/Tipping Trailer/TippingTrailer-C2RhSgR1.jpeg', '["\/assets\/products_staging\/implements\/Tipping Trailer\/TippingTrailer-C2RhSgR1.jpeg"]', '["Heavy-Duty Steel Construction","Hydraulic Tipping Mechanism","Various Payload Capacities","Multi-Leaf Spring Suspension"]', 'Active', 'Highly efficient transport and automated unloading of harvested crops, fertilizer bags, and loose farm materials.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (21, 'Lovol H754 H-Series 4WD Utility Tractor', 'Tractors', 'The Lovol H754 H-Series is an exceptionally engineered, multifunctional utility tractor independently developed to deliver unmatched power and adaptability for small to medium-sized farms. Powered by a robust Xinchai 4-cylinder engine, it satisfies modern emission regulations while providing an impressive torque reserve coefficient of over 30% and a heavy traction force reaching up to 17 KN. Built to survive challenging environments, it features a specialized shared-oil chassis integrated with a chassis oil radiator that continuously optimizes thermal control and overall operational efficiency during deep tillage or long hauling tasks.', 'Price on Request', '/assets/products_staging/tractor/LOVOL/WhatsApp Image 2026-07-09 at 11.33.23 AM (1).jpeg', '["\/assets\/products_staging\/tractor\/LOVOL\/WhatsApp Image 2026-07-09 at 11.33.23 AM (1).jpeg","\/assets\/products_staging\/tractor\/LOVOL\/WhatsApp Image 2026-07-09 at 11.33.27 AM.jpeg","\/assets\/products_staging\/tractor\/LOVOL\/WhatsApp Image 2026-07-09 at 11.33.28 AM.jpeg","\/assets\/products_staging\/tractor\/LOVOL\/WhatsApp Image 2026-07-09 at 11.33.29 AM.jpeg","\/assets\/products_staging\/tractor\/LOVOL\/WhatsApp Image 2026-07-09 at 11.33.34 AM (1).jpeg","\/assets\/products_staging\/tractor\/LOVOL\/WhatsApp Image 2026-07-09 at 11.33.34 AM.jpeg"]', '["75 HP Engine","Xinchai 4-Cylinder Water-Cooled Diesel Engine","12 Forward + 12 Reverse Gears with Mechanical Synchronizer Shuttle Shift","Heavy-Duty 4WD","Category II Three-Point Hitch with dual auxiliary cylinders","and Independent Dual-Speed PTO (540\/1000 RPM)"]', 'Active', 'Highly efficient dry and paddy field operations, deep plowing, rotary tillage, farm hauling, and heavy-duty front/rear implement attachments.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (22, 'Massey Ferguson MF-375 Utility Tractor', 'Tractors', 'The Massey Ferguson MF-375 is a legendary, durable, and highly versatile utility tractor engineered specifically to tackle demanding agricultural tasks under challenging field conditions. Powered by a robust and fuel-efficient 4-cylinder Perkins engine, it delivers high pulling power and maximum torque at low RPMs, minimizing engine wear while maximizing field productivity. Its aerodynamic body profile is paired with an upgraded oil cooler system to ensure steady engine performance without overheating during prolonged operations in hot climates.  The tractor''s heavy-duty transmission and independent 540 RPM PTO allow it to seamlessly operate deep-tillage implements, large planters, and harvesting tools. For operator safety and comfort, it features an oil-immersed multi-disc braking system for responsive stopping power, responsive hydrostatic steering to lower steering effort, and a spring-suspension seat designed to absorb vibrations during long working days in the field.', 'Price on Request', '/assets/products_staging/tractor/MF/WhatsApp Image 2026-07-09 at 11.33.35 AM (1).jpeg', '["\/assets\/products_staging\/tractor\/MF\/WhatsApp Image 2026-07-09 at 11.33.35 AM (1).jpeg","\/assets\/products_staging\/tractor\/MF\/WhatsApp Image 2026-07-09 at 11.33.35 AM.jpeg","\/assets\/products_staging\/tractor\/MF\/WhatsApp Image 2026-07-09 at 11.33.43 AM.jpeg","\/assets\/products_staging\/tractor\/MF\/WhatsApp Image 2026-07-09 at 11.33.44 AM.jpeg"]', '["75 HP Engine","4.41L 4-Cylinder Perkins Diesel Engine","Sliding Spur Transmission (8 Forward \/ 2 Reverse Gears)","2","145 kg Maximum Lifting Capacity","Hydrostatic Power Steering"]', 'Active', 'High-efficiency primary cultivation, heavy-duty plowing, medium-to-large scale crop hauling, and reliable multi-implement farm management.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (23, 'Zoomlion RC Series 1104 - 4WD Heavy-Duty Tractor', 'Tractors', 'The Zoomlion RC Series 1104 is a heavy-duty agricultural tractor designed to dominate demanding farm tasks. Featuring 16 forward speeds and an advanced 110 HP engine, it delivers high torque to pull wider implements and deep-subsoilers effortlessly. The advanced cabin ergonomics and technological control loops allow operators to remain productive during extended seasonal windows.', 'Price on Request', '/assets/products_staging/tractor/Zoomlion RC SERIES 1104 - 4WD /WhatsApp Image 2026-07-09 at 11.32.55 AM.jpeg', '["\/assets\/products_staging\/tractor\/Zoomlion RC SERIES 1104 - 4WD \/WhatsApp Image 2026-07-09 at 11.32.55 AM.jpeg","\/assets\/products_staging\/tractor\/Zoomlion RC SERIES 1104 - 4WD \/WhatsApp Image 2026-07-09 at 11.32.56 AM.jpeg","\/assets\/products_staging\/tractor\/Zoomlion RC SERIES 1104 - 4WD \/WhatsApp Image 2026-07-09 at 11.33.01 AM.jpeg","\/assets\/products_staging\/tractor\/Zoomlion RC SERIES 1104 - 4WD \/WhatsApp Image 2026-07-09 at 11.33.46 AM (1).jpeg"]', '["110 HP Engine","4WD","16 Forward Gears","High-Pressure Common Rail Diesel Engine","High Lifting Capacity Category II Hitch"]', 'Active', 'Intensive large-scale farming, deep tillage, heavy secondary cultivation, and continuous heavy machinery pulling.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (24, 'Zoomlion RK Series 504 - 4WD Compact Tractor', 'Tractors', 'The Zoomlion RK Series 504 delivers efficient performance in a compact, highly maneuverable 4WD frame. It is specially built to navigate narrow rows and smaller plots without sacrificing the hydraulic and pulling power required for plowing and planting. Its high fuel efficiency and straightforward operation make it a staple tool for diverse small-scale farmers.', 'Price on Request', '/assets/products_staging/tractor/Zoomlion RK SERIES 504K - 4WD/WhatsApp Image 2026-07-09 at 11.32.55 AM.jpeg', '["\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 504K - 4WD\/WhatsApp Image 2026-07-09 at 11.32.55 AM.jpeg","\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 504K - 4WD\/WhatsApp Image 2026-07-09 at 11.32.58 AM.jpeg","\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 504K - 4WD\/WhatsApp Image 2026-07-09 at 11.33.01 AM.jpeg","\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 504K - 4WD\/WhatsApp Image 2026-07-09 at 11.33.46 AM (1).jpeg"]', '["50 HP Engine","4WD","Compact Frame Design","Shuttle Shift Transmission","Multi-Way Hydraulic Valve System"]', 'Active', 'Perfect for small-to-medium farms, orchards, vineyard management, and tight-space maneuverability.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (25, 'Zoomlion RK Series 754 - 4WD Tractor', 'Tractors', 'The Zoomlion RK Series 754 provides outstanding versatility and power for modern farming conditions. Featuring a robust 12-speed transmission and dual-stage clutch mechanics, it gives the operator precise control over ground speeds and PTO speeds. Its aggressive 4WD axle enables steady operation through heavy clay and undulating topographies.', 'Price on Request', '/assets/products_staging/tractor/Zoomlion RK SERIES 754 - 4WD/WhatsApp Image 2026-07-09 at 11.33.02 AM (1).jpeg', '["\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 754 - 4WD\/WhatsApp Image 2026-07-09 at 11.33.02 AM (1).jpeg","\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 754 - 4WD\/WhatsApp Image 2026-07-09 at 11.33.02 AM.jpeg","\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 754 - 4WD\/WhatsApp Image 2026-07-09 at 11.33.23 AM.jpeg","\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 754 - 4WD\/WhatsApp Image 2026-07-09 at 11.33.45 AM.jpeg","\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 754 - 4WD\/WhatsApp Image 2026-07-09 at 11.33.46 AM.jpeg"]', '["75 HP Engine","4WD","12 Forward Gears","Dual-Stage Clutch","Ergonomic Operator Platform"]', 'Active', 'Powerful general agriculture, row-crop cultivation, medium-scale seeding, and intensive field spraying.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO public."products" ("id", "name", "category", "description", "price", "image", "images", "specs", "status", "task", "created_at", "updated_at", "is_new_arrival") VALUES (26, 'Zoomlion RK Series 904 - 4WD Heavy-Duty Tractor', 'Tractors', 'The Zoomlion RK Series 904 is a heavy-duty agricultural tractor designed to dominate demanding farm tasks. Featuring 16 forward speeds and an advanced 90 HP engine, it delivers high torque to pull wider implements and deep-subsoilers effortlessly. The advanced cabin ergonomics and technological control loops allow operators to remain productive during extended seasonal windows.', 'Price on Request', '/assets/products_staging/tractor/Zoomlion RK SERIES 904 - 4WD/WhatsApp Image 2026-07-09 at 11.32.55 AM.jpeg', '["\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 904 - 4WD\/WhatsApp Image 2026-07-09 at 11.32.55 AM.jpeg","\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 904 - 4WD\/WhatsApp Image 2026-07-09 at 11.33.01 AM.jpeg","\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 904 - 4WD\/WhatsApp Image 2026-07-09 at 11.33.22 AM (1).jpeg","\/assets\/products_staging\/tractor\/Zoomlion RK SERIES 904 - 4WD\/WhatsApp Image 2026-07-09 at 11.33.46 AM (1).jpeg"]', '["90 HP Engine","4WD","16 Forward Gears","High-Pressure Common Rail Diesel Engine","High Lifting Capacity Category II Hitch"]', 'Active', 'Intensive large-scale farming, deep tillage, heavy secondary cultivation, and continuous heavy machinery pulling.', '2026-07-18 21:26:19', '2026-07-18 21:26:19', FALSE) ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('public.products', 'id'), COALESCE((SELECT MAX(id) FROM public.products), 1));

-- Restore gallery_items (1 records)
INSERT INTO public."gallery_items" ("id", "title", "category", "image", "created_at", "updated_at", "video_url", "description", "date") VALUES (1, 'Test Title Python', NULL, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==', '2026-07-12 17:12:06', '2026-07-12 17:12:06', NULL, 'This is a summary of the test upload.', 'July 12, 2026') ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('public.gallery_items', 'id'), COALESCE((SELECT MAX(id) FROM public.gallery_items), 1));

-- Restore activities (16 records)
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (1, 'ECOWAS Delegation Partnership Visit', 'ecowas-delegation-partnership-visit', 'July 2026', 'A photographic record of the high-level ECOWAS delegation visiting our modern agricultural machinery hub and warehousing facilities.', '["\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.47 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.48 PM (1).jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.48 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.49 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.50 PM (1).jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.50 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.52 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.53 PM (1).jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.53 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.54 PM (1).jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.54 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.22.55 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.23.03 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.23.04 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.23.06 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.23.13 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.23.16 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.23.17 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.23.18 PM (1).jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.23.18 PM.jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.23.21 PM (1).jpeg","\/assets\/gallery\/ECOWAS\/WhatsApp Image 2026-07-13 at 3.23.21 PM.jpeg"]', '2026-07-13 14:52:48', '2026-07-13 14:52:48', 'A photographic record of the high-level ECOWAS delegation visiting our modern agricultural machinery hub and warehousing facilities.', 'ECOWAS Visit', NULL, 'A photographic record of the high-level ECOWAS delegation visiting our modern agricultural machinery hub and warehousing facilities.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (2, 'Regional Agricultural Machinery Field Excursion', 'regional-agricultural-machinery-field-excursion', 'June 2026', 'Documenting field operations, tractor demonstrations, and technical machinery excursions across farming communities.', '["\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.21 PM.jpeg","\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.28 PM (1).jpeg","\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.28 PM.jpeg","\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.29 PM (1).jpeg","\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.29 PM (2).jpeg","\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.29 PM.jpeg","\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.30 PM (1).jpeg","\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.30 PM (2).jpeg","\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.30 PM.jpeg","\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.31 PM (1).jpeg","\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.31 PM.jpeg","\/assets\/gallery\/EXCURSION\/WhatsApp Image 2026-07-13 at 3.17.32 PM.jpeg"]', '2026-07-13 14:52:48', '2026-07-13 14:52:48', 'Documenting field operations, tractor demonstrations, and technical machinery excursions across farming communities.', 'Excursion', NULL, 'Documenting field operations, tractor demonstrations, and technical machinery excursions across farming communities.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (3, 'Student Study Tour & Practical Training Day', 'student-study-tour-practical-training-day', 'May 2026', 'Providing hands-on exposure to Massey Ferguson and Lovol implements, guiding next-generation agricultural engineering students.', '["\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.13 PM (1).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.13 PM.jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.15 PM (1).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.15 PM (2).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.15 PM.jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.16 PM (1).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.16 PM (2).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.16 PM.jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.17 PM (1).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.17 PM.jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.21 PM (1).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.21 PM.jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.22 PM (1).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.22 PM (2).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.22 PM (3).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.22 PM.jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.23 PM (1).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.23 PM (2).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.23 PM.jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.27 PM (1).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.27 PM.jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.28 PM (1).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.28 PM.jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.29 PM (1).jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.29 PM.jpeg","\/assets\/gallery\/STUDENT VISIT\/WhatsApp Image 2026-07-13 at 3.14.30 PM.jpeg"]', '2026-07-13 14:52:48', '2026-07-13 14:52:48', 'Providing hands-on exposure to Massey Ferguson and Lovol implements, guiding next-generation agricultural engineering students.', 'Student Visit', NULL, 'Providing hands-on exposure to Massey Ferguson and Lovol implements, guiding next-generation agricultural engineering students.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (8, 'Visit to Zoomlion Agricultural Machinery Complex', 'visit-to-zoomlion-china-1', 'July 2026', 'Visit to Zoomlion Agricultural Machinery Complex during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.28.10 PM.jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion Agricultural Machinery Complex in China.', 'Our Company', NULL, 'Visit to Zoomlion Agricultural Machinery Complex during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (9, 'Visit to Zoomlion Machinery Manufacturing Hub', 'visit-to-zoomlion-china-2', 'July 2026', 'Visit to Zoomlion Machinery Manufacturing Hub during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.28.19 PM.jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion Machinery Manufacturing Hub in China.', 'Our Company', NULL, 'Visit to Zoomlion Machinery Manufacturing Hub during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (10, 'Visit to Zoomlion Combine Harvester Assembly Line', 'visit-to-zoomlion-china-3', 'July 2026', 'Visit to Zoomlion Combine Harvester Assembly Line during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.28.20 PM.jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion Combine Harvester Assembly Line in China.', 'Our Company', NULL, 'Visit to Zoomlion Combine Harvester Assembly Line during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (11, 'Visit to Zoomlion Technology & Innovation Exhibition', 'visit-to-zoomlion-china-4', 'July 2026', 'Visit to Zoomlion Technology & Innovation Exhibition during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.28.21 PM.jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion Technology & Innovation Exhibition in China.', 'Our Company', NULL, 'Visit to Zoomlion Technology & Innovation Exhibition during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (12, 'Visit to Zoomlion Global Partner Monument & Headquarters', 'visit-to-zoomlion-china-5', 'July 2026', 'Visit to Zoomlion Global Partner Monument & Headquarters during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.28.32 PM.jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion Global Partner Monument & Headquarters in China.', 'Our Company', NULL, 'Visit to Zoomlion Global Partner Monument & Headquarters during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (13, 'Visit to Zoomlion Heavy Equipment Production Facility', 'visit-to-zoomlion-china-6', 'July 2026', 'Visit to Zoomlion Heavy Equipment Production Facility during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.28.44 PM.jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion Heavy Equipment Production Facility in China.', 'Our Company', NULL, 'Visit to Zoomlion Heavy Equipment Production Facility during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (14, 'Visit to Zoomlion Technical Excursion & Field Testing', 'visit-to-zoomlion-china-7', 'July 2026', 'Visit to Zoomlion Technical Excursion & Field Testing during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.28.48 PM.jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion Technical Excursion & Field Testing in China.', 'Our Company', NULL, 'Visit to Zoomlion Technical Excursion & Field Testing during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (15, 'Visit to Zoomlion Advanced Harvester Operations', 'visit-to-zoomlion-china-8', 'July 2026', 'Visit to Zoomlion Advanced Harvester Operations during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.29.21 PM.jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion Advanced Harvester Operations in China.', 'Our Company', NULL, 'Visit to Zoomlion Advanced Harvester Operations during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (16, 'Visit to Zoomlion High-Horsepower Tractor Center', 'visit-to-zoomlion-china-9', 'July 2026', 'Visit to Zoomlion High-Horsepower Tractor Center during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.29.22 PM (1).jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion High-Horsepower Tractor Center in China.', 'Our Company', NULL, 'Visit to Zoomlion High-Horsepower Tractor Center during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (17, 'Visit to Zoomlion Executive Partnership Exchange', 'visit-to-zoomlion-china-10', 'July 2026', 'Visit to Zoomlion Executive Partnership Exchange during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.29.22 PM (2).jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion Executive Partnership Exchange in China.', 'Our Company', NULL, 'Visit to Zoomlion Executive Partnership Exchange during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (18, 'Visit to Zoomlion International Distribution Hub', 'visit-to-zoomlion-china-11', 'July 2026', 'Visit to Zoomlion International Distribution Hub during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.29.22 PM.jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion International Distribution Hub in China.', 'Our Company', NULL, 'Visit to Zoomlion International Distribution Hub during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (19, 'Visit to Zoomlion Technical Demonstrations & Showcase', 'visit-to-zoomlion-china-12', 'July 2026', 'Visit to Zoomlion Technical Demonstrations & Showcase during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.29.23 PM (1).jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion Technical Demonstrations & Showcase in China.', 'Our Company', NULL, 'Visit to Zoomlion Technical Demonstrations & Showcase during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
INSERT INTO public."activities" ("id", "title", "slug", "date", "content", "image", "created_at", "updated_at", "summary", "category", "video_url", "description") VALUES (20, 'Visit to Zoomlion Agricultural Engineering Center', 'visit-to-zoomlion-china-13', 'July 2026', 'Visit to Zoomlion Agricultural Engineering Center during the official business trip to Zoomlion Heavy Industry headquarters in China.', '["/assets/gallery/OUR_COMPANY_NEW/WhatsApp Image 2026-07-21 at 4.29.23 PM.jpeg"]', '2026-07-24 14:25:03', '2026-07-24 14:25:03', 'Visit to Zoomlion Agricultural Engineering Center in China.', 'Our Company', NULL, 'Visit to Zoomlion Agricultural Engineering Center during the official business trip to Zoomlion Heavy Industry headquarters in China.') ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('public.activities', 'id'), COALESCE((SELECT MAX(id) FROM public.activities), 1));

-- Restore inquiries (1 records)
INSERT INTO public."inquiries" ("id", "name", "email", "subject", "message", "status", "date", "created_at", "updated_at") VALUES (1, 'John Doe', 'john@example.com', 'Tractor Quote', 'No message provided', 'Pending', '2026-07-07', '2026-07-07 19:39:13', '2026-07-07 19:39:13') ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('public.inquiries', 'id'), COALESCE((SELECT MAX(id) FROM public.inquiries), 1));
